services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: rsync -a public/ /data/public/ && npm run start
    healthCheckPath: /_health
    autoDeploy: true
    disk:
      name: strapi-data
      mountPath: /data
      sizeGB: 1
